### ISSUE TITLE
Clojure CLI support (deps.edn)

### ISSUE THREAD

**Issue by souenzzo** [tpope/vim-classpath#13]
`clojure -Spath` returns exactly the same thing that `lein classpath`

`lein with-profiles dev,cljs classpath` will became `clojure -A:dev:cljs -Spath`

I can answer any other clojure-related question.

**Comment by tpope** [comment]
What is this `clojure` command that takes a `-S`?

```
$ clojure -Spath
Exception in thread "main" java.io.FileNotFoundException: -Spath (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at clojure.lang.Compiler.loadFile(Compiler.java:7570)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$script_opt.invokeStatic(main.clj:512)
        at clojure.main$script_opt.invoke(main.clj:507)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
$ clojure --help
Usage: clojure [init-opt*] [main-opt] [arg*]

  With no options or args, runs an interactive Read-Eval-Print Loop

  init options:
    -i, --init path     Load a file or resource
    -e, --eval string   Evaluate expressions in string; print non-nil values

  main options:
    -m, --main ns-name  Call the -main function from a namespace with args
    -r, --repl          Run a repl
    path                Run a script from a file or resource
    -                   Run a script from standard input
    -h, -?, --help      Print this help message and exit

  operation:

    - Establishes thread-local bindings for commonly set!-able vars
    - Enters the user namespace
    - Binds *command-line-args* to a seq of strings containing command line
      args that appear after any main option
    - Runs all init options in order
    - Calls a -main function or runs a repl or script if requested

  The init options may be repeated and mixed freely, but must appear before
  any main option. The appearance of any eval option before running a repl
  suppresses the usual repl greeting message: "Clojure ~(clojure-version)".

  Paths may be absolute or relative in the filesystem or relative to
  classpath. Classpath-relative paths have prefix of @ or @/
```

**Comment by souenzzo** [comment]
Not sure about with `clojure` you are calling.
I'm calling this one: https://clojure.org/guides/getting_started#_installation_on_linux

Even older versions of  `clojure` include `-S` options... I do not know how to identify this help page

**Comment by tpope** [comment]
Looks like Ubuntu provides a different, less functional `clojure` wrapper. I wish I could say I was surprised.
